version: "3.8"

# secrets:
#   - NGINX_HOST=ghost
#   - NGINX_PORT=3000
#   - url=http://localhost
#   - database__client=mysql
#   - database__connection__host=db
#   - database__connection__user=root
#   - database__connection__password=changeme
#   - database__connection__database=ghost
#   - MYSQL_ROOT_PASSWORD=changeme

services:
  proxy:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "80:3000"

  ghost:
    image: ghost:3-alpine
    restart: always

  db:
    image: mysql:5.7
