version: "3.8"
services:
  proxy:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=ghost
      - NGINX_PORT=80

  ghost:
    image: ghost:3-alpine
