version: "3.8"

services:
  proxy:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "80:3000"
    environment:
      - NGINX_HOST=ghost
      - NGINX_PORT=3000

  ghost:
    image: ghost:3-alpine
    restart: always
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      - url=http://localhost
